steps:
# Build the container images
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/cloud-controller-backend:$COMMIT_SHA', '.',
    "--build-arg", "GPG_PRIVATE_KEY_PART_1=${_GPG_PRIVATE_KEY_PART_1}",
    "--build-arg", "GPG_PRIVATE_KEY_PART_2=${_GPG_PRIVATE_KEY_PART_2}"
  ]

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cloud-controller-backend:$COMMIT_SHA']

# Deploy Container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - "run"
    - "deploy"
    - "cloud-controller-backend"
    - "--image"
    - "gcr.io/$PROJECT_ID/cloud-controller-backend:$COMMIT_SHA"
    - "--region"
    - "us-central1"
    - "--platform"
    - "managed"
images:
  - "gcr.io/$PROJECT_ID/cloud-controller-backend:$COMMIT_SHA"
